#!/bin/zsh

FIRST_ARGUMENT="$1"

ssh -X pi@192.168.1.10;
# FIRST_ARGUMENT;


# scp pi@192.168.1.10:~/Desktop/OGbullshit/og_telnetserver/src/main.rs ~/Desktop/main.rs
# scp ~/.ssh/id_rsa.pub pi@192.168.1.10:~/.ssh/ 